public with sharing class RandomClass {

    public RandomClass(){
        System.debug('Hej');
        System.debug('HejIgen');
        System.debug('HejIgenIgen');
        System.debug('HejIgenIgenIgenIgen');
        System.debug('Wow');
        System.debug('Testar igen');
        System.debug('Testar igen igen Igen Igen Igen');
    }
    
    public static Integer additionTest(Integer a, Integer b){
        return a + b;
    }
    
}