name: Salesforce CI

# Workflow for pr to integration branch and sandbox.
# Commenting to test random change. Want to see repport.

on:
    pull_request:
        branches:
            - integration

jobs:
    scan-and-test:
        runs-on: ubuntu-latest
        environment:
            name: integration

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"

            - name: Install Salesforce CLI
              run: |
                  npm install @salesforce/cli --global

            - name: "Installing sfdx git delta"
              run: |
                  echo y | sfdx plugins:install sfdx-git-delta
                  sfdx plugins

            - name: Set up Java 17
              uses: actions/setup-java@v4
              with:
                  distribution: "corretto"
                  java-version: "17"

            - name: "Installing SFDX scanner"
              run: sf plugins install @salesforce/sfdx-scanner

            - name: Authenticate to Integration Org
              run: |
                  sf org login sfdx-url --set-default --sfdx-url-file <(echo "${{ secrets.SFDX_AUTH_URL }}")

            - name: "Create delta packages for new, modified or deleted metadata"
              run: |
                  mkdir changed-sources
                  sfdx sgd:source:delta --from "HEAD~1" --output changed-sources/ --generate-delta --source force-app/

            - name: "Scan code"
              run: |
                  cd changed-sources
                  sf scanner run --format sarif --target './**/*.cls' --category "Design,Best Practices,Performance" --outfile 'apexScanResults.sarif' 
                  cd ..

            - name: Upload SARIF file
              uses: github/codeql-action/upload-sarif@v3
              with:
                  sarif_file: changed-sources/apexScanResults.sarif

            - name: "Run tests"
              run: |
                  sf project deploy start --dry-run --manifest changed-sources/package/package.xml --test-level RunLocalTests > test_results.txt
                  echo "TEST_RESULTS_PATH=test_results.txt" >> $GITHUB_ENV

            - name: "Parse SARIF and Test Results"
              run: |

                  node parseSarif.js changed-sources/apexScanResults.sarif > sarif_summary.txt
                  echo "SARIF_SUMMARY_PATH=sarif_summary.txt" >> $GITHUB_ENV

                  node parseTestResults.js test_results.txt > test_summary.txt
                  echo "TEST_SUMMARY_PATH=test_summary.txt" >> $GITHUB_ENV

            - name: Post results to PR
              uses: actions/github-script@v7
              with:
                  github-token: ${{secrets.GITHUB_TOKEN}}
                  script: |
                      const issue_number = context.issue.number;
                      const fs = require('fs');
                      const sarif_summary = fs.readFileSync(process.env.SARIF_SUMMARY_PATH, 'utf8');
                      const test_summary = fs.readFileSync(process.env.TEST_SUMMARY_PATH, 'utf8');
                      github.rest.issues.createComment({
                        issue_number: issue_number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: "### Code Scan Summary:\n```\n" + sarif_summary + "\n```\n### Test Summary:\n```\n" + test_summary + "\n```"
                      });
