name: Integration PR

on:
  pull_request:
    branches:
      - integration

jobs:
  quality-check-integration-pr:
    runs-on: ubuntu-latest
    environment:
      name: integration
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup dependencies
        run: |
          npm install @salesforce/cli --global
          echo y | sfdx plugins:install sfdx-git-delta
          sfdx plugins
          sf plugins install @salesforce/sfdx-scanner
          actions/setup-java@v4
          with:
            distribution: "corretto"
            java-version: "17"

      - name: Authenticate and prepare environment
        run: |
          sf org login sfdx-url --set-default --sfdx-url-file <(echo "${{ secrets.SFDX_AUTH_URL }}")
          mkdir changed-sources
          sfdx sgd:source:delta --to "HEAD" --from "HEAD~1" --output changed-sources/ --generate-delta --source force-app/

      - name: Run tests and post results
        run: |
          sf project deploy start --dry-run --manifest changed-sources/package/package.xml --post-destructive-changes changed-sources/destructiveChanges/destructiveChanges.xml --test-level RunLocalTests --verbose > test_results.txt || echo "Tests failed, but results will still be posted."
          cat test_results.txt
          echo "::set-output name=tests_failed::$?"
        continue-on-error: true

      - name: Post test results to PR
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.issue.number;
            const fs = require('fs');
            const test_results = fs.readFileSync('test_results.txt', 'utf8');
            const codeScanningUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/security/code-scanning`;
            github.rest.issues.createComment({
              issue_number: issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### Code Scan Results:\n[View Code Scanning Alerts](${codeScanningUrl})\n### Test Results:\n\`\`\`${test_results}\`\`\``
            });
