name: Integration PR

on:
    pull_request:
        branches:
            - integration

jobs:
    scan-and-test:
        runs-on: ubuntu-latest
        environment:
            name: integration

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"

            - name: Install Salesforce CLI
              run: |
                  npm install @salesforce/cli --global

            - name: "Installing sfdx git delta"
              run: |
                  echo y | sfdx plugins:install sfdx-git-delta
                  sfdx plugins

            - name: Set up Java 17
              uses: actions/setup-java@v4
              with:
                  distribution: "corretto"
                  java-version: "17"

            - name: "Installing SFDX scanner"
              run: sf plugins install @salesforce/sfdx-scanner

            - name: Authenticate to Integration Org
              run: |
                  sf org login sfdx-url --set-default --sfdx-url-file <(echo "${{ secrets.SFDX_AUTH_URL }}")

            - name: "Create delta packages for new, modified or deleted metadata"
              run: |
                  mkdir changed-sources
                  sfdx sgd:source:delta --from "HEAD~1" --output changed-sources/ --generate-delta --source force-app/

            - name: "Run tests and get coverage"
              run: |
                  sf project deploy start --dry-run --manifest changed-sources/package/package.xml --test-level RunLocalTests > test_results.txt
                    sfdx force:apex:test:run --codecoverage --resultformat json --outputdir ./test-results --wait 10
                    echo "TEST_RESULTS_PATH=test_results.txt" >> $GITHUB_ENV
                    echo "COVERAGE_RESULTS_PATH=./test-results/test-result-codecoverage.json" >> $GITHUB_ENV

            - name: Post results and coverage to PR
              uses: actions/github-script@v7
              with:
                  github-token: ${{secrets.GITHUB_TOKEN}}
                  script: |
                      const issue_number = context.issue.number;
                      const fs = require('fs');
                      const test_results = fs.readFileSync(process.env.TEST_RESULTS_PATH, 'utf8');
                      const coverage_results = JSON.parse(fs.readFileSync(process.env.COVERAGE_RESULTS_PATH, 'utf8'));
                      const coverageSummary = `Total Coverage: ${coverage_results.totalCoverage}%`;
                      const branchName = context.payload.pull_request.head.ref;
                      const codeScanningUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/security/code-scanning?query=is%3Aopen+branch%3A${branchName}`;
                      github.rest.issues.createComment({
                        issue_number: issue_number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: `### Code Scan Results:\n[View Code Scanning Alerts](${codeScanningUrl})\n### Test Results:\n\`\`\`${test_results}\`\`\`\n### Code Coverage:\n\`\`\`${coverageSummary}\`\`\``
                      });
